server:
  port: 5000
  shutdown: graceful

spring:
  application:
    name: converter

api:
  # FIXME: Одно и то же конфигурируется два раза.
  currency:
    url: https://api.coinbase.com/v2/
    timeout: 3000 # ms
  exchange-rates:
    url: https://api.coinbase.com/v2/
    timeout: 3000 # ms
