server:
  port: 5000
  shutdown: graceful

spring:
  application:
    name: converter

api:
  coinbase:
    base-url: https://api.coinbase.com/v2/
    timeout: 3s

cache:
  currency-list:
    expire-after-write: 1m
  currency-rate:
    maximum-size: 1024
    expire-after-write: 1m
